slam_toolbox:
  ros__parameters:
    # Robot 2 frame parameters
    odom_frame: carter2/odom
    base_frame: carter2/base_link
    map_frame: map
    
    # Scan matching parameters
    use_scan_matching: true
    use_scan_bagging: true
    scan_topic: /carter2/front_3d_lidar/lidar_points
    mode: mapping  # mapping or localization

    # Map update and resolution parameters
    resolution: 0.05
    map_update_interval: 5.0
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    update_periodical: 3.0
    
    # SLAM parameters
    max_update_rate: 10.0
    publish_occupancy_map: true
    transform_publish_period: 0.05
    map_optimize_interval: 3.0
    max_laser_range: 20.0
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
    
    # Correlation parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
    
    # Correlation parameters - coarse
    coarse_search_space_dimension: 0.5
    coarse_search_space_resolution: 0.01
    coarse_search_space_smear_deviation: 0.1
    
    # Registration parameters
    fine_search_angle_offset: 0.00349  # ~0.2 degrees
    coarse_search_angle_offset: 0.349   # ~20 degrees
    coarse_angle_resolution: 0.0349     # ~2 degrees
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true