controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

simple_velocity_controller:
  ros__parameters:
    joints:
      - drive_wheel_joint_left
      - drive_wheel_joint_right
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity