name: ROS 2 CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y python3-pip lcov
        pip3 install gcovr
        
    - name: Create workspace and copy package
      run: |
        mkdir -p /ros2_ws/src
        cp -r $GITHUB_WORKSPACE /ros2_ws/src/cpp_pkg
        
    - name: Install package dependencies
      run: |
        cd /ros2_ws
        rosdep update
        rosdep install --from-paths src --ignore-src -y
        
    - name: Build with coverage flags
      run: |
        cd /ros2_ws
        colcon build --cmake-args -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
        
    - name: Run tests
      run: |
        cd /ros2_ws
        source install/setup.bash
        colcon test
        colcon test-result --verbose
        
    - name: Generate coverage report
      run: |
        cd /ros2_ws/build/cpp_pkg
        gcovr --xml coverage.xml --exclude-unreachable-branches --exclude-throw-branches
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: /ros2_ws/build/cpp_pkg/coverage.xml
        fail_ci_if_error: true