name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y python3-colcon-common-extensions lcov gcovr
        rosdep update
        rosdep install --from-paths . --ignore-src -r -y
        
    - name: Build with coverage flags
      run: |
        . /opt/ros/humble/setup.sh
        colcon build --packages-select frontier_explorer \
          --cmake-args -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_FLAGS="--coverage" \
          -DCMAKE_EXE_LINKER_FLAGS="--coverage"

    - name: Run tests
      run: |
        . /opt/ros/humble/setup.sh
        . install/setup.sh
        colcon test --packages-select frontier_explorer --event-handlers console_direct+
        colcon test-result --verbose

    - name: Generate coverage report
      run: |
        . /opt/ros/humble/setup.sh
        . install/setup.sh
        
        # Create coverage report
        lcov --directory build/frontier_explorer --capture \
          --output-file coverage.info
          
        # Filter out system and test files
        lcov --remove coverage.info \
          '/opt/*' '/usr/*' '*/test/*' \
          --output-file coverage.filtered
          
        # Generate HTML report
        genhtml coverage.filtered \
          --output-directory coverage_report

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage_report